### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by elBelgg** [Rxflex/kubek-minecraft-dashboard#2]
Hi, there is a new version of Kubek (3.0.5). Just to remind you to update and release it

**Comment by Rxflex** [comment]
Thanks for the reminder, I'll see what has been added and fixed in the new version and make an update.

**Comment by Rxflex** [comment]
I looked at the changes, there is no point in updating, since all the author did was change the links to his site and moved the server ID generation function to a separate file. No new features have been added, and no problems have been fixed.

https://github.com/Seeroy/kubek-minecraft-dashboard/commit/10276b4fd199a1f5331c50633f906742dce61616
